---
abstract: 'Module to validate if data is valid currency'
author:
  - 'Daniel Culver'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::Most: 0
  perl: 5.006
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validate-Currency
requires:
  Carp: 0
  Exporter: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/dculver1986/data-validate-currency/issues
  homepage: http://search.cpan.org/dist/Data-Validate-Currency
  repository: git://github.com/dculver1986/data-validate-currency.git
version: 0.1.0
